name: Build and Push Vue or Spring Boot Images

on:
  push:
    branches:
      - main
    paths:
      - 'vue-frontend/**'
      - 'vite-frontend/**'
      - 'springboot-backend/**'
      - 'go-gost/**'
      - 'android-app/**'
      - '.github/workflows/docker-build.yml'

jobs:
  build-gost:
    if: contains(github.event.head_commit.message, '[skip gost]') == false
    name: Build & Compress GOST Binary
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install UPX
        run: |
          wget https://github.com/upx/upx/releases/download/v4.2.1/upx-4.2.1-amd64_linux.tar.xz
          tar -xf upx-4.2.1-amd64_linux.tar.xz
          sudo mv upx-4.2.1-amd64_linux/upx /usr/local/bin/
          rm -rf upx-4.2.1-amd64_linux*

      - name: Build GOST binary
        working-directory: ./go-gost
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o gost

      - name: Compress with UPX
        working-directory: ./go-gost
        run: |
          upx --best --lzma gost

      - name: Create or Update Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git tag -f gost-latest ${{ github.sha }}
          git push origin gost-latest --force
          sleep 3
          if gh release view gost-latest 2>/dev/null; then
            echo "Release exists, updating assets"
          else
            gh release create gost-latest \
              --target ${{ github.sha }} \
              --title "GOST Binary Latest" \
              --notes "GOST binary compiled from commit ${{ github.sha }}\n\n- Platform: Linux AMD64\n- Compressed with UPX\n- Build date: ${{ github.event.head_commit.timestamp }}" \
              --repo ${{ github.repository }}
          fi
          gh release upload gost-latest ./go-gost/gost --clobber

  build-vite:
    if: contains(github.event.head_commit.message, '[skip vite]') == false
    name: Build & Push Vite Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Vite image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -t zijingcuan/vite-frontend \
            ./vite-frontend

  build-java:
    if: contains(github.event.head_commit.message, '[skip java]') == false
    name: Build & Push Spring Boot Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK and Maven
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Java JAR
        working-directory: ./springboot-backend
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Java image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -t zijingcuan/springboot-backend \
            ./springboot-backend
